name: Android Build

#env:
#  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#  FIREBASE_APP_ID: your_firebase_app_id

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - development

jobs:

  Local Test Job:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Print Java version
        run: javac -version

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'